#!/bin/sh
#
# Open a file
#   - CTRL-O to open with `open` command,
#   - CTRL-E or Enter key to open with the $EDITOR

IFS=$'\n' out=("$(fzf-tmux --query="$1" --exit-0 --expect=ctrl-o,ctrl-e)")
key=$(head -1 <<< "${out}")
file=$(head -2 <<< "${out}" | tail -1)
if [[ -n "$file" ]]; then
    if [[ "$key" = ctrl-o ]]; then
            open "$file"
    else
            ${EDITOR:-vim} "$file"
    fi
fi