#!/bin/sh
#
# list my custom commands

echo "Custom commands:"
echo "bcp           -> brew clean package"
echo "bip           -> brew install package"
echo "bup           -> brew upgrade package"
echo "c             -> \`charm .\`"
echo "copy          -> copy from file or stdin"
echo "cpw           -> copy password"
echo "fbr           -> git checkout branch"
echo "fix-postgres  -> fix broken brew postgres"
echo "fo            -> open file (CTRL-O to use \`open\`)"
echo "gog			      -> run git commands on subdirectories"
echo "gray			    -> turn everything grayscale"
echo "kill <TAB>    -> kill with fzf"
echo "paste         -> pbpaste"
echo "peng          -> display a notification"
echo "pjson         -> prettify json"
echo "ssh **<TAB>   -> fuzzy host matching"
echo "hog           -> execute mercurial commands on all repos in this directory"
