#!/usr/bin/env bash
if [ "$1" = "-v" ] ; then
    VERBOSE=1
    shift
else
    VERBOSE=0
fi

for i in * ; do
  if [ -d $i/.hg ] ; then
    cd $i;
    if [ $VERBOSE = 1 ] ; then
        echo Verzeichnis: $i
     fi
     hg "$@";
     cd ..;
  fi
done
